# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: encrypted_communication.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1d\x65ncrypted_communication.proto\x12*aea.cryptor.encrypted_communication.v1_0_0\"\xf4\n\n\x1d\x45ncryptedCommunicationMessage\x12\x8d\x01\n\x15\x63ommunication_request\x18\x05 \x01(\x0b\x32l.aea.cryptor.encrypted_communication.v1_0_0.EncryptedCommunicationMessage.Communication_Request_PerformativeH\x00\x12\x8f\x01\n\x16\x63ommunication_response\x18\x06 \x01(\x0b\x32m.aea.cryptor.encrypted_communication.v1_0_0.EncryptedCommunicationMessage.Communication_Response_PerformativeH\x00\x12\x85\x01\n\x11\x65nd_communication\x18\x07 \x01(\x0b\x32h.aea.cryptor.encrypted_communication.v1_0_0.EncryptedCommunicationMessage.End_Communication_PerformativeH\x00\x12m\n\x05\x65rror\x18\x08 \x01(\x0b\x32\\.aea.cryptor.encrypted_communication.v1_0_0.EncryptedCommunicationMessage.Error_PerformativeH\x00\x12\x8f\x01\n\x16initiate_communication\x18\t \x01(\x0b\x32m.aea.cryptor.encrypted_communication.v1_0_0.EncryptedCommunicationMessage.Initiate_Communication_PerformativeH\x00\x1a\x86\x02\n\tErrorCode\x12u\n\nerror_code\x18\x01 \x01(\x0e\x32\x61.aea.cryptor.encrypted_communication.v1_0_0.EncryptedCommunicationMessage.ErrorCode.ErrorCodeEnum\"\x81\x01\n\rErrorCodeEnum\x12\x16\n\x12INVALID_PUBLIC_KEY\x10\x00\x12\x14\n\x10\x45NCRYPTION_ERROR\x10\x01\x12\x14\n\x10\x44\x45\x43RYPTION_ERROR\x10\x02\x12\x13\n\x0fINVALID_MESSAGE\x10\x03\x12\x17\n\x13\x43OMMUNICATION_ERROR\x10\x04\x1a\x39\n#Initiate_Communication_Performative\x12\x12\n\npublic_key\x18\x01 \x01(\t\x1aN\n\"Communication_Request_Performative\x12\x19\n\x11\x65ncrypted_message\x18\x01 \x01(\t\x12\r\n\x05nonce\x18\x02 \x01(\t\x1aO\n#Communication_Response_Performative\x12\x19\n\x11\x65ncrypted_message\x18\x01 \x01(\t\x12\r\n\x05nonce\x18\x02 \x01(\t\x1a \n\x1e\x45nd_Communication_Performative\x1a\x90\x01\n\x12\x45rror_Performative\x12g\n\nerror_code\x18\x01 \x01(\x0b\x32S.aea.cryptor.encrypted_communication.v1_0_0.EncryptedCommunicationMessage.ErrorCode\x12\x11\n\terror_msg\x18\x02 \x01(\tB\x0e\n\x0cperformativeb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'encrypted_communication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_ENCRYPTEDCOMMUNICATIONMESSAGE']._serialized_start = 78
    _globals['_ENCRYPTEDCOMMUNICATIONMESSAGE']._serialized_end = 1474
    _globals['_ENCRYPTEDCOMMUNICATIONMESSAGE_ERRORCODE']._serialized_start = 795
    _globals['_ENCRYPTEDCOMMUNICATIONMESSAGE_ERRORCODE']._serialized_end = 1057
    _globals['_ENCRYPTEDCOMMUNICATIONMESSAGE_ERRORCODE_ERRORCODEENUM']._serialized_start = 928
    _globals['_ENCRYPTEDCOMMUNICATIONMESSAGE_ERRORCODE_ERRORCODEENUM']._serialized_end = 1057
    _globals['_ENCRYPTEDCOMMUNICATIONMESSAGE_INITIATE_COMMUNICATION_PERFORMATIVE']._serialized_start = 1059
    _globals['_ENCRYPTEDCOMMUNICATIONMESSAGE_INITIATE_COMMUNICATION_PERFORMATIVE']._serialized_end = 1116
    _globals['_ENCRYPTEDCOMMUNICATIONMESSAGE_COMMUNICATION_REQUEST_PERFORMATIVE']._serialized_start = 1118
    _globals['_ENCRYPTEDCOMMUNICATIONMESSAGE_COMMUNICATION_REQUEST_PERFORMATIVE']._serialized_end = 1196
    _globals['_ENCRYPTEDCOMMUNICATIONMESSAGE_COMMUNICATION_RESPONSE_PERFORMATIVE']._serialized_start = 1198
    _globals['_ENCRYPTEDCOMMUNICATIONMESSAGE_COMMUNICATION_RESPONSE_PERFORMATIVE']._serialized_end = 1277
    _globals['_ENCRYPTEDCOMMUNICATIONMESSAGE_END_COMMUNICATION_PERFORMATIVE']._serialized_start = 1279
    _globals['_ENCRYPTEDCOMMUNICATIONMESSAGE_END_COMMUNICATION_PERFORMATIVE']._serialized_end = 1311
    _globals['_ENCRYPTEDCOMMUNICATIONMESSAGE_ERROR_PERFORMATIVE']._serialized_start = 1314
    _globals['_ENCRYPTEDCOMMUNICATIONMESSAGE_ERROR_PERFORMATIVE']._serialized_end = 1458
# @@protoc_insertion_point(module_scope)
