agent_name: innovation_station_app
author: eightballer
version: 0.1.0
license: Apache-2.0
description: Agent implementing the innovation station app.
aea_version: '>=1.35.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- eightballer/http_client:0.1.0:bafybeif5a4v2iifbungunult2lc2b4bvwuld5hebojyjod2e4esckbez7y
- eightballer/http_server:0.1.0:bafybeies7jer6ezp2gxx7f7aw4t64rcgepqprqr3cqukc726wci3xspdom
- valory/abci:0.1.0:bafybeiaoc6rfvirsdlsi4nwa3kycz2gdcqyahdwpfvy6sf7hfv23hhklfy
- valory/http_client:0.23.0:bafybeiaqrxod7thwar3rpeajcru7y6hhyeshsinwolnen52w6gzhu43lmu
- valory/ipfs:0.1.0:bafybeieymwm2o7qp3aybimpsw75qwrqsdqeq764sqlhggookgitncituwa
- valory/ledger:0.19.0:bafybeiaztbj35abn7et2nfprhqknbuembxvldy46cv3xwnciqg7aelzaim
- valory/p2p_libp2p_client:0.1.0:bafybeidfm65eece533hfvg2xyn4icpmvz4lmvbemstrlo3iuffb7e72ycq
contracts:
- valory/service_registry:0.1.0:bafybeie7cd7jtclhycsqovtaoiu6lqyusr4d7eplin6o6onjsqwd63mrvu
protocols:
- eightballer/http:0.1.0:bafybeihmhy6ax5uyjt7yxppn4viqswibcs5lsjhl3kvrsesorqe2u44jcm
- open_aea/signing:1.0.0:bafybeig7ijceilgb22q7yg65jok7n5bmo3uogezpz4tltmil2xh7ib6e5q
- valory/abci:0.1.0:bafybeifsttranjnxstpoyswpm2dzfyzimpatdfbu5pdpu7ibmda5x24ipe
- valory/acn:1.1.0:bafybeif2th25e4gaejgpg373wal4bkpyfxdbee7f7gbrb64vrgrwhbakxm
- valory/contract_api:1.0.0:bafybeib3abpck4a6a63vyymd2pdiwijdsqk43hrrxz734v5ghxje46pxgm
- valory/http:1.0.0:bafybeieshrrplt5oadws5tz3rhjo6m2spchdyhkwa2z6ze2bs4ivauusfq
- valory/ipfs:0.1.0:bafybeidjn5fa2tjah3jif4tt67rccvtflkmkj5gnjq2jssdkxdzwrzzasy
- valory/ledger_api:1.0.0:bafybeidltb2fvcfokf7a2i3jnrf4kmmsn5bxmcrwdtbz2nrrzhpj4dlzwe
- valory/tendermint:0.1.0:bafybeib25ulpp3tri3ppexk4t6yttuajhr7wpgs7wajpsnbbnzo256ubem
skills:
- eightballer/innovation_abci:0.1.0:bafybeifiuzjsct4gn5jvpai6q2ifvrkuc6mygo3acjo27emyswaa3gdd7e
- eightballer/innovation_station_api:0.1.0:bafybeiezrjtfyttg4nrmpmgorsppz7gepiywys5ijafeb6rhymbpw5g6ta
- eightballer/innovation_station_chained_app:0.1.0:bafybeieyuwmou32tlemqyitlhmtyk37xdebgpciycjdjrtamhhraabsiam
- valory/abstract_abci:0.1.0:bafybeiexad4gxpw4g3443lb5aufw477lgcpgtx44lklyo5hay2vhwz5g3e
- valory/abstract_round_abci:0.1.0:bafybeih2eokievudt4a7x7dwd6uyan7cgwr3y2t4dtvzy4xsubbbumf34m
- valory/registration_abci:0.1.0:bafybeig3jo3fhcxz7xgwpxnmf74ann2bwlqyaq2466wrkg5mbc33wmpk6y
- valory/reset_pause_abci:0.1.0:bafybeicuma62mkfb36ygsycufhjqt6jqffi7zhhuxdlgdvmq6kcjl2ebm4
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  open-aea-ledger-ethereum: {}
default_connection: null
---
public_id: valory/abci:0.1.0:bafybeihofnsokowicviac6yz3uhur52l3mf54s2hz4i2je5ie4vlruouga
type: connection
config:
  host: ${str:localhost}
  port: ${int:26658}
  target_skill_id: eightballer/innovation_station_chained_app:0.1.0
  use_tendermint: false
---
public_id: eightballer/innovation_station_chained_app:0.1.0:bafybeigskx4hyktjzm6iiro7ublfpp6e6ypibznaquo3l4b5meuwdpjvma
type: skill
models:
  params:
    args:
      use_termination: false
      setup:
        consensus_threshold: 1
        safe_contract_address: '0x0000000000000000000000000000000000000000'
        all_participants:
        - ${MAS_ADDRESS:str:0x0000000000000000000000000000000000000000}
---
public_id: eightballer/http_server:0.1.0
type: connection
config:
  target_skill_id: eightballer/innovation_station_api:0.1.0
  port: 8080
  host: 0.0.0.0
---
public_id: eightballer/innovation_station_api:0.1.0:bafybeifrtrzzdemrrlya45f3atvn45rrbdoezur45rpvglhcaxdv33goyy
type: skill
models:
  strategy:
    args:
      frontend:
        enabled: ${FRONTEND_ENABLED:bool:true}
        ipfs_hash: ${str:bafybeihqsbmbgxjnzi6fwz5cfmg4mydocdtgvbhhfhizn5k3zyq7r4b2fu}
        directory: www
        openai_api_key: ${str:}
