# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messaging_bot_protocol.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1cmessaging_bot_protocol.proto\x12+aea.developer.messaging_bot_protocol.v0_1_0\"\xc0\t\n\x1bMessagingBotProtocolMessage\x12z\n\x0c\x62ot_response\x18\x05 \x01(\x0b\x32\x62.aea.developer.messaging_bot_protocol.v0_1_0.MessagingBotProtocolMessage.Bot_Response_PerformativeH\x00\x12l\n\x05\x65rror\x18\x06 \x01(\x0b\x32[.aea.developer.messaging_bot_protocol.v0_1_0.MessagingBotProtocolMessage.Error_PerformativeH\x00\x12\x80\x01\n\x0freceive_message\x18\x07 \x01(\x0b\x32\x65.aea.developer.messaging_bot_protocol.v0_1_0.MessagingBotProtocolMessage.Receive_Message_PerformativeH\x00\x12z\n\x0csend_message\x18\x08 \x01(\x0b\x32\x62.aea.developer.messaging_bot_protocol.v0_1_0.MessagingBotProtocolMessage.Send_Message_PerformativeH\x00\x1a\xe3\x01\n\tErrorCode\x12t\n\nerror_code\x18\x01 \x01(\x0e\x32`.aea.developer.messaging_bot_protocol.v0_1_0.MessagingBotProtocolMessage.ErrorCode.ErrorCodeEnum\"`\n\rErrorCodeEnum\x12\x18\n\x14MESSAGE_SEND_FAILURE\x10\x00\x12\x1b\n\x17MESSAGE_RECEIVE_FAILURE\x10\x01\x12\x18\n\x14\x42OT_RESPONSE_FAILURE\x10\x02\x1a]\n\x19Send_Message_Performative\x12\x14\n\x0crecipient_id\x18\x01 \x01(\t\x12\x17\n\x0fmessage_content\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x05\x1a]\n\x1cReceive_Message_Performative\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x17\n\x0fmessage_content\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x05\x1aX\n\x19\x42ot_Response_Performative\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\x12\x18\n\x10response_content\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x05\x1a\xa9\x01\n\x12\x45rror_Performative\x12\x66\n\nerror_code\x18\x01 \x01(\x0b\x32R.aea.developer.messaging_bot_protocol.v0_1_0.MessagingBotProtocolMessage.ErrorCode\x12\x11\n\terror_msg\x18\x02 \x01(\t\x12\x18\n\x10\x65rror_msg_is_set\x18\x03 \x01(\x08\x42\x0e\n\x0cperformativeb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messaging_bot_protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_MESSAGINGBOTPROTOCOLMESSAGE']._serialized_start = 78
    _globals['_MESSAGINGBOTPROTOCOLMESSAGE']._serialized_end = 1294
    _globals['_MESSAGINGBOTPROTOCOLMESSAGE_ERRORCODE']._serialized_start = 599
    _globals['_MESSAGINGBOTPROTOCOLMESSAGE_ERRORCODE']._serialized_end = 826
    _globals['_MESSAGINGBOTPROTOCOLMESSAGE_ERRORCODE_ERRORCODEENUM']._serialized_start = 730
    _globals['_MESSAGINGBOTPROTOCOLMESSAGE_ERRORCODE_ERRORCODEENUM']._serialized_end = 826
    _globals['_MESSAGINGBOTPROTOCOLMESSAGE_SEND_MESSAGE_PERFORMATIVE']._serialized_start = 828
    _globals['_MESSAGINGBOTPROTOCOLMESSAGE_SEND_MESSAGE_PERFORMATIVE']._serialized_end = 921
    _globals['_MESSAGINGBOTPROTOCOLMESSAGE_RECEIVE_MESSAGE_PERFORMATIVE']._serialized_start = 923
    _globals['_MESSAGINGBOTPROTOCOLMESSAGE_RECEIVE_MESSAGE_PERFORMATIVE']._serialized_end = 1016
    _globals['_MESSAGINGBOTPROTOCOLMESSAGE_BOT_RESPONSE_PERFORMATIVE']._serialized_start = 1018
    _globals['_MESSAGINGBOTPROTOCOLMESSAGE_BOT_RESPONSE_PERFORMATIVE']._serialized_end = 1106
    _globals['_MESSAGINGBOTPROTOCOLMESSAGE_ERROR_PERFORMATIVE']._serialized_start = 1109
    _globals['_MESSAGINGBOTPROTOCOLMESSAGE_ERROR_PERFORMATIVE']._serialized_end = 1278
# @@protoc_insertion_point(module_scope)
