name: innovation_station
author: eightballer
version: 0.1.0
description: An agent service to allow for the creation of new components. Built with
  love at ETHNYC 2023 by 8Baller, Asha, and Zarathustra. A number of novel firsts
  have been accomplished. First agent service to act as a CDN for a frontend. Implements
  additional http protocols, allowing for the handling of multiple http protocols
  within the same agent. This allows the seperation of the cdn, which is pulled from
  from ipfs by hash on agent startup.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint: {}
fingerprint_ignore_patterns: []
agent: eightballer/innovation_station_app:0.1.0:bafybeidlfynkqzu4xcazwz4pvmzyrutiflmzokkozspwddo6kye27bzfva
number_of_agents: 1
deployment:
  agent:
    ports:
      0:
        8001: 26658
---
public_id: eightballer/http_server:0.1.0:bafybeicabdn272rslxezvzifkmny36c3s2hpyeahsoqorctys7uq6b3djq
type: connection
config:
  target_skill_id: eightballer/innovation_station_api:0.1.0
  port: 26658
  host: 0.0.0.0
---
public_id: eightballer/innovation_station_api:0.1.0:bafybeic7mkotgalbblew3g43nof554n2oeskbif6iiukbhntidy2ovz6ve
type: skill
models:
  strategy:
    args:
      frontend:
        enabled: true
        ipfs_hash: ${IPFS_HASH:str:}
        directory: www
        openai_api_key: ${OPENAI_API_KEY:str:}
