name: innovation_station
author: eightballer
version: 0.1.0
description: An agent service to allow for the creation of new components. Built with
  love at ETHNYC 2023 by Eightballer, Asiya, and Zarathustra.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint: {}
fingerprint_ignore_patterns: []
agent: eightballer/innovation_station:0.1.0:bafybeibwqdpkkbgqjenubuqxc77lfob7vteaqqq4kzzza7spp2bsfa36vm
number_of_agents: 1
deployment:
  agent:
    ports:
      0:
        8001: 26658
---
public_id: eightballer/http_server:0.1.0:bafybeicabdn272rslxezvzifkmny36c3s2hpyeahsoqorctys7uq6b3djq
type: connection
config:
  target_skill_id: eightballer/innovation_station_api:0.1.0
  port: 26658
  host: 0.0.0.0
---
public_id: eightballer/innovation_station_api:0.1.0:bafybeifrtrzzdemrrlya45f3atvn45rrbdoezur45rpvglhcaxdv33goyy
type: skill
models:
  strategy:
    args:
      frontend:
        enabled: true
        ipfs_hash: ${IPFS_HASH:str:bafybeihqsbmbgxjnzi6fwz5cfmg4mydocdtgvbhhfhizn5k3zyq7r4b2fu}
        directory: www
