# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lint_protocol.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13lint_protocol.proto\x12 aea.devteam.lint_protocol.v1_0_0\"\xe9\t\n\x13LintProtocolMessage\x12i\n\rinitiate_lint\x18\x05 \x01(\x0b\x32P.aea.devteam.lint_protocol.v1_0_0.LintProtocolMessage.Initiate_Lint_PerformativeH\x00\x12i\n\rlint_complete\x18\x06 \x01(\x0b\x32P.aea.devteam.lint_protocol.v1_0_0.LintProtocolMessage.Lint_Complete_PerformativeH\x00\x12\x63\n\nlint_error\x18\x07 \x01(\x0b\x32M.aea.devteam.lint_protocol.v1_0_0.LintProtocolMessage.Lint_Error_PerformativeH\x00\x12\x63\n\nlint_issue\x18\x08 \x01(\x0b\x32M.aea.devteam.lint_protocol.v1_0_0.LintProtocolMessage.Lint_Issue_PerformativeH\x00\x1a\xb3\x01\n\tErrorCode\x12\x61\n\nerror_code\x18\x01 \x01(\x0e\x32M.aea.devteam.lint_protocol.v1_0_0.LintProtocolMessage.ErrorCode.ErrorCodeEnum\"C\n\rErrorCodeEnum\x12\x10\n\x0c\x43ONFIG_ERROR\x10\x00\x12\x10\n\x0cLINT_FAILURE\x10\x01\x12\x0e\n\nPATH_ERROR\x10\x02\x1a\x9b\x01\n\x08Severity\x12]\n\x08severity\x18\x01 \x01(\x0e\x32K.aea.devteam.lint_protocol.v1_0_0.LintProtocolMessage.Severity.SeverityEnum\"0\n\x0cSeverityEnum\x12\x08\n\x04INFO\x10\x00\x12\x0b\n\x07WARNING\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x1aY\n\x1aInitiate_Lint_Performative\x12\x14\n\x0cproject_path\x18\x01 \x01(\t\x12\x0e\n\x06\x63onfig\x18\x02 \x01(\t\x12\x15\n\rconfig_is_set\x18\x03 \x01(\x08\x1a\xbf\x01\n\x17Lint_Issue_Performative\x12\x10\n\x08issue_id\x18\x01 \x01(\t\x12P\n\x08severity\x18\x02 \x01(\x0b\x32>.aea.devteam.lint_protocol.v1_0_0.LintProtocolMessage.Severity\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0c\n\x04line\x18\x04 \x01(\x05\x12\x0e\n\x06\x63olumn\x18\x05 \x01(\x05\x12\x11\n\tfile_path\x18\x06 \x01(\t\x1a-\n\x1aLint_Complete_Performative\x12\x0f\n\x07summary\x18\x01 \x01(\t\x1a\x81\x01\n\x17Lint_Error_Performative\x12S\n\nerror_code\x18\x01 \x01(\x0b\x32?.aea.devteam.lint_protocol.v1_0_0.LintProtocolMessage.ErrorCode\x12\x11\n\terror_msg\x18\x02 \x01(\tB\x0e\n\x0cperformativeb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lint_protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_LINTPROTOCOLMESSAGE']._serialized_start = 58
    _globals['_LINTPROTOCOLMESSAGE']._serialized_end = 1315
    _globals['_LINTPROTOCOLMESSAGE_ERRORCODE']._serialized_start = 498
    _globals['_LINTPROTOCOLMESSAGE_ERRORCODE']._serialized_end = 677
    _globals['_LINTPROTOCOLMESSAGE_ERRORCODE_ERRORCODEENUM']._serialized_start = 610
    _globals['_LINTPROTOCOLMESSAGE_ERRORCODE_ERRORCODEENUM']._serialized_end = 677
    _globals['_LINTPROTOCOLMESSAGE_SEVERITY']._serialized_start = 680
    _globals['_LINTPROTOCOLMESSAGE_SEVERITY']._serialized_end = 835
    _globals['_LINTPROTOCOLMESSAGE_SEVERITY_SEVERITYENUM']._serialized_start = 787
    _globals['_LINTPROTOCOLMESSAGE_SEVERITY_SEVERITYENUM']._serialized_end = 835
    _globals['_LINTPROTOCOLMESSAGE_INITIATE_LINT_PERFORMATIVE']._serialized_start = 837
    _globals['_LINTPROTOCOLMESSAGE_INITIATE_LINT_PERFORMATIVE']._serialized_end = 926
    _globals['_LINTPROTOCOLMESSAGE_LINT_ISSUE_PERFORMATIVE']._serialized_start = 929
    _globals['_LINTPROTOCOLMESSAGE_LINT_ISSUE_PERFORMATIVE']._serialized_end = 1120
    _globals['_LINTPROTOCOLMESSAGE_LINT_COMPLETE_PERFORMATIVE']._serialized_start = 1122
    _globals['_LINTPROTOCOLMESSAGE_LINT_COMPLETE_PERFORMATIVE']._serialized_end = 1167
    _globals['_LINTPROTOCOLMESSAGE_LINT_ERROR_PERFORMATIVE']._serialized_start = 1170
    _globals['_LINTPROTOCOLMESSAGE_LINT_ERROR_PERFORMATIVE']._serialized_end = 1299
# @@protoc_insertion_point(module_scope)
