agent_name: innovation_station
author: eightballer
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.35.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- eightballer/http_client:0.1.0:bafybeieflx5vltakecgjhi5xdtabsq3mgjpbm32bhywt72n4fuajznd6uy
- eightballer/http_server:0.1.0:bafybeib5jgc7ktpxpctgz6xhheirf5nllur4czf5mgmu4dkp7fr7afjo54
- valory/abci:0.1.0:bafybeic7lgi4semmxje6rzopuzedevbtaamk5pnv7c3mc7jdi6zrpmr6pi
contracts: []
protocols:
- eightballer/http:0.1.0:bafybeidvkgr7coyezng2xqru23otzb47s57zyybgaug46sznsc4za6ltju
- open_aea/signing:1.0.0:bafybeicrpy5tyvayhulbzemzberi6ezhgcxz4y7qmh32wd5x3n2npb7ksy
- valory/abci:0.1.0:bafybeiajowytsskxt6hfsgra27lgswiw3wrbb57yfxlxieqbc3uomudr7u
- valory/http:1.0.0:bafybeifyoio7nlh5zzyn5yz7krkou56l22to3cwg7gw5v5o3vxwklibhty
skills:
- eightballer/innovation_station_api:0.1.0:bafybeifiojchwdhqjkl2kiwqke73ia4sv3tyyer3tvy7hw7cy3rdcap5ea
- valory/abstract_abci:0.1.0:bafybeibk7zylaspf62plu6637bsm4sli6qgfvb6jxdxagm7ahxf4pqrbh4
- valory/abstract_round_abci:0.1.0:bafybeige5xfsbjkuyi5sx6kdxjfgprl64sn5j5iba2kv4smhg453cf4m6u
- zarathustra/subgraph_query:0.1.0:bafybeifgst2sxm6qzpe6izzkfffpfn255yrqlijvxopwyan2eu4uvvvl7i
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  open-aea-ledger-cosmos: {}
  open-aea-ledger-ethereum: {}
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: zarathustra/subgraph_query:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: eightballer/http_server:0.1.0:bafybeicabdn272rslxezvzifkmny36c3s2hpyeahsoqorctys7uq6b3djq
type: connection
config:
  target_skill_id: eightballer/innovation_station_api:0.1.0
  port: 26658
  host: 0.0.0.0
---
public_id: eightballer/innovation_station_api:0.1.0:bafybeifrtrzzdemrrlya45f3atvn45rrbdoezur45rpvglhcaxdv33goyy
type: skill
models:
  strategy:
    args:
      frontend:
        enabled: ${FRONTEND_ENABLED:bool:true}
        ipfs_hash: ${IPFS_HASH:str:bafybeihqsbmbgxjnzi6fwz5cfmg4mydocdtgvbhhfhizn5k3zyq7r4b2fu}
        directory: www
