# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lint_protocol.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13lint_protocol.proto\x12$aea.eightballer.lint_protocol.v0_1_0\"\xf1\t\n\x13LintProtocolMessage\x12]\n\x05\x65rror\x18\x05 \x01(\x0b\x32L.aea.eightballer.lint_protocol.v0_1_0.LintProtocolMessage.Error_PerformativeH\x00\x12m\n\rinitiate_lint\x18\x06 \x01(\x0b\x32T.aea.eightballer.lint_protocol.v0_1_0.LintProtocolMessage.Initiate_Lint_PerformativeH\x00\x12o\n\x0elint_completed\x18\x07 \x01(\x0b\x32U.aea.eightballer.lint_protocol.v0_1_0.LintProtocolMessage.Lint_Completed_PerformativeH\x00\x12g\n\nlint_issue\x18\x08 \x01(\x0b\x32Q.aea.eightballer.lint_protocol.v0_1_0.LintProtocolMessage.Lint_Issue_PerformativeH\x00\x1a\xca\x01\n\tErrorCode\x12\x65\n\nerror_code\x18\x01 \x01(\x0e\x32Q.aea.eightballer.lint_protocol.v0_1_0.LintProtocolMessage.ErrorCode.ErrorCodeEnum\"V\n\rErrorCodeEnum\x12\x1a\n\x16LINT_EXECUTION_FAILURE\x10\x00\x12\x17\n\x13INVALID_SOURCE_PATH\x10\x01\x12\x10\n\x0cLINT_TIMEOUT\x10\x02\x1a\xa4\x01\n\x08Severity\x12\x66\n\rseverity_code\x18\x01 \x01(\x0e\x32O.aea.eightballer.lint_protocol.v0_1_0.LintProtocolMessage.Severity.SeverityEnum\"0\n\x0cSeverityEnum\x12\x08\n\x04INFO\x10\x00\x12\x0b\n\x07WARNING\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x1a\x36\n\x1aInitiate_Lint_Performative\x12\x18\n\x10source_code_path\x18\x01 \x01(\t\x1a\xac\x01\n\x17Lint_Issue_Performative\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\x12\x0c\n\x04line\x18\x02 \x01(\x05\x12\x0e\n\x06\x63olumn\x18\x03 \x01(\x05\x12T\n\x08severity\x18\x04 \x01(\x0b\x32\x42.aea.eightballer.lint_protocol.v0_1_0.LintProtocolMessage.Severity\x12\x0f\n\x07message\x18\x05 \x01(\t\x1a\x44\n\x1bLint_Completed_Performative\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x0cissues_count\x18\x02 \x01(\x05\x1a\x80\x01\n\x12\x45rror_Performative\x12W\n\nerror_code\x18\x01 \x01(\x0b\x32\x43.aea.eightballer.lint_protocol.v0_1_0.LintProtocolMessage.ErrorCode\x12\x11\n\terror_msg\x18\x02 \x01(\tB\x0e\n\x0cperformativeb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lint_protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_LINTPROTOCOLMESSAGE']._serialized_start = 62
    _globals['_LINTPROTOCOLMESSAGE']._serialized_end = 1327
    _globals['_LINTPROTOCOLMESSAGE_ERRORCODE']._serialized_start = 510
    _globals['_LINTPROTOCOLMESSAGE_ERRORCODE']._serialized_end = 712
    _globals['_LINTPROTOCOLMESSAGE_ERRORCODE_ERRORCODEENUM']._serialized_start = 626
    _globals['_LINTPROTOCOLMESSAGE_ERRORCODE_ERRORCODEENUM']._serialized_end = 712
    _globals['_LINTPROTOCOLMESSAGE_SEVERITY']._serialized_start = 715
    _globals['_LINTPROTOCOLMESSAGE_SEVERITY']._serialized_end = 879
    _globals['_LINTPROTOCOLMESSAGE_SEVERITY_SEVERITYENUM']._serialized_start = 831
    _globals['_LINTPROTOCOLMESSAGE_SEVERITY_SEVERITYENUM']._serialized_end = 879
    _globals['_LINTPROTOCOLMESSAGE_INITIATE_LINT_PERFORMATIVE']._serialized_start = 881
    _globals['_LINTPROTOCOLMESSAGE_INITIATE_LINT_PERFORMATIVE']._serialized_end = 935
    _globals['_LINTPROTOCOLMESSAGE_LINT_ISSUE_PERFORMATIVE']._serialized_start = 938
    _globals['_LINTPROTOCOLMESSAGE_LINT_ISSUE_PERFORMATIVE']._serialized_end = 1110
    _globals['_LINTPROTOCOLMESSAGE_LINT_COMPLETED_PERFORMATIVE']._serialized_start = 1112
    _globals['_LINTPROTOCOLMESSAGE_LINT_COMPLETED_PERFORMATIVE']._serialized_end = 1180
    _globals['_LINTPROTOCOLMESSAGE_ERROR_PERFORMATIVE']._serialized_start = 1183
    _globals['_LINTPROTOCOLMESSAGE_ERROR_PERFORMATIVE']._serialized_end = 1311
# @@protoc_insertion_point(module_scope)
