# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: testing_workflow.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16testing_workflow.proto\x12%aea.developer.testing_workflow.v0_1_0\"\xd9\t\n\x16TestingWorkflowMessage\x12\x61\n\x05\x65rror\x18\x05 \x01(\x0b\x32P.aea.developer.testing_workflow.v0_1_0.TestingWorkflowMessage.Error_PerformativeH\x00\x12m\n\x0bstart_tests\x18\x06 \x01(\x0b\x32V.aea.developer.testing_workflow.v0_1_0.TestingWorkflowMessage.Start_Tests_PerformativeH\x00\x12w\n\x10test_case_result\x18\x07 \x01(\x0b\x32[.aea.developer.testing_workflow.v0_1_0.TestingWorkflowMessage.Test_Case_Result_PerformativeH\x00\x12u\n\x0ftests_completed\x18\x08 \x01(\x0b\x32Z.aea.developer.testing_workflow.v0_1_0.TestingWorkflowMessage.Tests_Completed_PerformativeH\x00\x1a\xdf\x01\n\tErrorCode\x12i\n\nerror_code\x18\x01 \x01(\x0e\x32U.aea.developer.testing_workflow.v0_1_0.TestingWorkflowMessage.ErrorCode.ErrorCodeEnum\"g\n\rErrorCodeEnum\x12\x1a\n\x16TEST_EXECUTION_FAILURE\x10\x00\x12\x15\n\x11INVALID_TEST_CASE\x10\x01\x12\x11\n\rTIMEOUT_ERROR\x10\x02\x12\x10\n\x0cSYSTEM_ERROR\x10\x03\x1aG\n\x18Start_Tests_Performative\x12\x17\n\x0ftest_suite_name\x18\x01 \x01(\t\x12\x12\n\ntest_cases\x18\x02 \x03(\t\x1a\x96\x01\n\x1dTest_Case_Result_Performative\x12\x16\n\x0etest_case_name\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0e\n\x06output\x18\x03 \x01(\t\x12\x15\n\routput_is_set\x18\x04 \x01(\x08\x12\x0e\n\x06\x65rrors\x18\x05 \x03(\t\x12\x15\n\rerrors_is_set\x18\x06 \x01(\x08\x1a\xa1\x01\n\x1cTests_Completed_Performative\x12\x17\n\x0ftest_suite_name\x18\x01 \x01(\t\x12\x13\n\x0btotal_tests\x18\x02 \x01(\x05\x12\x14\n\x0cpassed_tests\x18\x03 \x01(\x05\x12\x14\n\x0c\x66\x61iled_tests\x18\x04 \x01(\x05\x12\x0f\n\x07summary\x18\x05 \x01(\t\x12\x16\n\x0esummary_is_set\x18\x06 \x01(\x08\x1a\x84\x01\n\x12\x45rror_Performative\x12[\n\nerror_code\x18\x01 \x01(\x0b\x32G.aea.developer.testing_workflow.v0_1_0.TestingWorkflowMessage.ErrorCode\x12\x11\n\terror_msg\x18\x02 \x01(\tB\x0e\n\x0cperformativeb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'testing_workflow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals['_TESTINGWORKFLOWMESSAGE']._serialized_start = 66
    _globals['_TESTINGWORKFLOWMESSAGE']._serialized_end = 1307
    _globals['_TESTINGWORKFLOWMESSAGE_ERRORCODE']._serialized_start = 543
    _globals['_TESTINGWORKFLOWMESSAGE_ERRORCODE']._serialized_end = 766
    _globals['_TESTINGWORKFLOWMESSAGE_ERRORCODE_ERRORCODEENUM']._serialized_start = 663
    _globals['_TESTINGWORKFLOWMESSAGE_ERRORCODE_ERRORCODEENUM']._serialized_end = 766
    _globals['_TESTINGWORKFLOWMESSAGE_START_TESTS_PERFORMATIVE']._serialized_start = 768
    _globals['_TESTINGWORKFLOWMESSAGE_START_TESTS_PERFORMATIVE']._serialized_end = 839
    _globals['_TESTINGWORKFLOWMESSAGE_TEST_CASE_RESULT_PERFORMATIVE']._serialized_start = 842
    _globals['_TESTINGWORKFLOWMESSAGE_TEST_CASE_RESULT_PERFORMATIVE']._serialized_end = 992
    _globals['_TESTINGWORKFLOWMESSAGE_TESTS_COMPLETED_PERFORMATIVE']._serialized_start = 995
    _globals['_TESTINGWORKFLOWMESSAGE_TESTS_COMPLETED_PERFORMATIVE']._serialized_end = 1156
    _globals['_TESTINGWORKFLOWMESSAGE_ERROR_PERFORMATIVE']._serialized_start = 1159
    _globals['_TESTINGWORKFLOWMESSAGE_ERROR_PERFORMATIVE']._serialized_end = 1291
# @@protoc_insertion_point(module_scope)
